-- Plataforma de destinos | 07: los negocios de La Fortuna
-- Investigacion web del 30/08/2026. El estado_verificacion refleja la calidad
-- real de la fuente: nada se marca verificado sin telefono o correo confirmado
-- en fuente oficial. De 29 fichas, 9 lo estan.

with datos (categoria, nombre, babosa, email, telefono, whatsapp, sitio_web,
            resumen_es, resumen_en, descripcion_es, descripcion_en,
            direccion, rango_precio, verificacion, atributos) as (values

('parques-nacionales','Parque Nacional Volcán Arenal','parque-nacional-volcan-arenal',
 'acahn.pnvolcanarenal@sinac.go.cr','+50622004192',null,'https://sinac.go.cr/ES/ac/ACAHN/pnva/',
 'El parque del volcán, con senderos sobre antiguas coladas de lava.',
 'The volcano national park, with trails over old lava flows.',
 'Área protegida con dos sectores, Península y Volcán, y dos conos: el Arenal, activo, y el Chato, inactivo y con una laguna dentro del cráter. Los senderos señalizados recorren bosque secundario y campos de lava endurecida, con recorridos de hora y media a tres horas. No hay venta de entradas en línea: se compran en la boletería el mismo día.',
 'A protected area with two sectors and two cones: Arenal, still active, and Chato, dormant with a lagoon inside its crater. Marked trails cross secondary forest and hardened lava fields, on walks of one and a half to three hours. Tickets are not sold online: you buy them at the gate the day of your visit.',
 'Ruta 142, 16 km al oeste de La Fortuna','economico','verificado',
 '{"entrada_extranjeros_usd":15,"entrada_nacionales_crc":1130,"abre":"08:00","cierra":"16:00","administrado_por":"SINAC"}'),

('cataratas','Catarata Río Fortuna','catarata-rio-fortuna',
 null,'+50624799515',null,'https://www.cataratalafortuna.com',
 'Caída de más de 70 metros al final de unos 500 escalones.',
 'A 70-metre drop at the bottom of some 500 steps.',
 'La postal de La Fortuna: una caída de más de setenta metros que termina en una poza de agua clara, a seis kilómetros del centro. Se baja por una escalera de unos quinientos escalones, y hay que volver a subirlos. La administra ADIFORT, la asociación de desarrollo de La Fortuna, que reinvierte lo recaudado en proyectos de la comunidad.',
 'The postcard shot of La Fortuna: a drop of over seventy metres ending in a clear pool, six kilometres from town. You climb down some five hundred steps, and you climb back up. It is run by ADIFORT, the local development association, which reinvests the fees in community projects.',
 '6 km al sur del centro de La Fortuna','moderado','verificado',
 '{"altura_metros":70,"escalones":500,"administrado_por":"ADIFORT"}'),

('puentes-colgantes','Mistico Arenal Hanging Bridges Park','mistico-arenal-hanging-bridges-park',
 'marketing@misticopark.com','+50624798282',null,'https://misticopark.com',
 'Catorce puentes colgantes sobre el dosel del bosque, en 3,2 km.',
 'Fourteen hanging bridges over the forest canopy, along 3.2 km.',
 'Un circuito de 3,2 kilómetros con catorce puentes colgantes suspendidos sobre el dosel del bosque, que se recorre en menos de dos horas. Es de los mejores sitios de la zona para ver monos congo, perezosos, tucanes y ranas de colores, y en días despejados el volcán aparece completo. Tiene parqueo amplio, restaurante, tienda y transporte desde los hoteles.',
 'A 3.2-kilometre circuit with fourteen hanging bridges suspended over the forest canopy, walkable in under two hours. One of the best spots in the area to see howler monkeys, sloths, toucans and brightly coloured frogs, and on clear days the volcano shows in full.',
 '2 km al este de la represa del Lago Arenal, La Fortuna 21007','moderado','verificado',
 '{"puentes":14,"longitud_km":3.2,"duracion_horas":2}'),

('vida-silvestre','Ecocentro Danaus','ecocentro-danaus',
 null,null,null,'https://ecocentrodanaus.com',
 'Reserva privada con mariposario, laguna y casa Maleku.',
 'Private reserve with butterfly garden, lagoon and a Maleku house.',
 'Reserva ecológica privada dedicada a la educación ambiental y la conservación, a cuatro kilómetros del centro. Su mariposario alberga varias especies, entre ellas el morfo azul. Completan el recorrido una laguna natural, un estanque de ranas y reptiles y una casa tradicional del pueblo Maleku. Tiene Bandera Azul Ecológica desde hace varios años seguidos.',
 'A private ecological reserve devoted to environmental education and conservation, four kilometres from town. Its butterfly garden holds several species, the blue morpho among them, plus a natural lagoon, a frog and reptile pond and a traditional Maleku house.',
 '4 km al este de La Fortuna','moderado','parcial',
 '{"reconocimientos":["Bandera Azul Ecologica"]}'),

('aguas-termales','Tabacón Thermal Resort & Spa','tabacon-thermal-resort-spa',
 null,'+50624792000',null,'https://www.tabacon.com',
 'Las termales más conocidas del Arenal, en un río caliente natural.',
 'The best-known hot springs in Arenal, along a natural hot river.',
 'Las aguas termales más conocidas de la zona. Cascadas y pozas construidas dentro del bosque lluvioso siguiendo el cauce del río Tabacón, que baja caliente desde el volcán. El resort cuenta con spa y hospedaje propio, y está certificado en sostenibilidad turística.',
 'The best-known hot springs in the area. Waterfalls and pools built into the rainforest along the Tabacon river, which runs hot straight down from the volcano. The resort has its own spa and lodging.',
 'Carretera a Nuevo Arenal, noroeste del centro','lujo','parcial',
 '{"tiene_hospedaje":true,"tiene_spa":true,"certificacion":"CST"}'),

('aguas-termales','Ecotermales Fortuna','ecotermales-fortuna',
 null,null,null,'https://ecotermalesfortuna.cr',
 'Seis pozas en el bosque, con aforo limitado a 80 personas por turno.',
 'Six forest pools, capped at 80 visitors per session.',
 'Seis pozas termales naturales metidas en el bosque, con una catarata de agua dulce y dos piscinas. Lo que las distingue es el aforo: no admiten más de ochenta visitantes por turno, así que se puede estar en silencio. Hay bar junto a las pozas y restaurante de comida costarricense. Operan desde 2002 en dos turnos.',
 'Six natural hot pools set in the forest, with a freshwater waterfall and two swimming pools. What sets them apart is the cap: no more than eighty visitors per session, so it stays quiet. Running since 2002 in two daily sessions.',
 'La Fortuna de San Carlos','alto','parcial',
 '{"pozas":6,"aforo_por_turno":80,"entrada_usd":49,"turnos":["09:00-16:00","16:00-21:30"],"opera_desde":2002}'),

('aguas-termales','Baldi Hot Springs Hotel Resort & Spa','baldi-hot-springs',
 null,null,null,'https://www.baldihotsprings.cr',
 'Veinticinco pozas, toboganes y bar dentro del agua.',
 'Twenty-five pools, water slides and a swim-up bar.',
 'Alrededor de veinticinco pozas termales de distintas temperaturas, con toboganes de agua, área de juegos para niños, bar dentro de la piscina, varios restaurantes y spa. Es la opción más orientada a grupos y familias que buscan pasarla bien más que estar en silencio.',
 'Around twenty-five thermal pools at different temperatures, with water slides, a childrens play area, a swim-up bar, several restaurants and a spa. Aimed at groups and families after a good time rather than quiet.',
 'Ruta 142, 21007, La Fortuna','alto','parcial',
 '{"pozas":25,"abre":"09:00","cierra":"22:00","tiene_hospedaje":true,"tiene_toboganes":true}'),

('aguas-termales','The Springs Resort & Spa','the-springs-resort-spa',
 null,null,null,'https://www.thespringscostarica.com',
 'Veintiocho pozas sobre una cresta, con cinco restaurantes.',
 'Twenty-eight pools on a mountain ridge, with five restaurants.',
 'Resort de cinco estrellas sobre una cresta montañosa de 165 acres, a veinte minutos del centro. Tiene veintiocho pozas termales a distintas alturas, cinco restaurantes y un parque de aventura propio. Es el complejo más grande de la zona y funciona como destino en sí mismo.',
 'A five-star resort on a 165-acre mountain ridge, twenty minutes from town. Twenty-eight thermal pools at different levels, five restaurants and its own adventure park.',
 'Carretera a Nuevo Arenal, La Fortuna','lujo','parcial',
 '{"pozas":28,"restaurantes":5,"acres":165,"tiene_hospedaje":true}'),

('aguas-termales','Paradise Hot Springs','paradise-hot-springs',
 null,null,null,null,
 'Termales tranquilas y de aforo pequeño, abiertas desde 2011.',
 'Quiet, small-capacity hot springs, open since 2011.',
 'Termales de perfil tranquilo y menor aforo que las grandes de la zona, abiertas desde 2011. Buena opción para quien busca bañarse sin multitudes y sin pagar tarifa de resort.',
 'Quiet hot springs with smaller capacity than the big complexes nearby, open since 2011. A good option for a soak without crowds and without resort pricing.',
 'La Fortuna de San Carlos','moderado','pendiente',
 '{"opera_desde":2011}'),

('lodges','Arenal Observatory Lodge & Trails','arenal-observatory-lodge',
 null,null,null,'https://www.arenalobservatorylodge.com',
 'El único hotel dentro del parque nacional, con senderos propios.',
 'The only hotel inside the national park, with its own trails.',
 'El único hotel dentro del Parque Nacional Volcán Arenal. Se construyó en 1987 como estación de investigación del Instituto Smithsonian, y todavía conserva ese aire de puesto de observación. Tiene senderos propios que bajan al lago y suben hacia las coladas de lava, y una de las vistas más cercanas al cono que se pueden tener durmiendo bajo techo.',
 'The only hotel inside Arenal Volcano National Park. Built in 1987 as a Smithsonian research station and it still carries that observation-post feel. Its own trails run down to the lake and up toward the lava flows.',
 'Dentro del Parque Nacional Volcán Arenal','alto','parcial',
 '{"opera_desde":1987,"tiene_senderos_propios":true,"dentro_del_parque":true}'),

('resorts','Arenal Springs Resort & Spa','arenal-springs-resort-spa',
 null,null,null,'https://hotelarenalspring.com',
 'Bungalows con vista al volcán y pozas termales propias.',
 'Bungalows with volcano views and on-site thermal pools.',
 'Resort de bungalows con vista frontal al volcán y pozas termales de agua caliente en la propiedad. Está sobre la carretera principal hacia el parque, lo bastante cerca del centro para bajar a cenar y lo bastante lejos para no oír el pueblo.',
 'A bungalow resort with a head-on volcano view and thermal pools on the property, along the main road toward the park.',
 'Carretera a Nuevo Arenal, La Fortuna','alto','parcial',
 '{"tiene_aguas_termales":true,"tipo_habitacion":"bungalow"}'),

('hoteles','Hotel La Pradera del Arenal','hotel-la-pradera-del-arenal',
 null,null,null,'https://lapraderadelarenal.com',
 'Hotel de precio medio a un kilómetro del centro.',
 'Mid-range hotel a kilometre from downtown.',
 'Hotel de precio medio sobre la carretera al volcán, a un kilómetro del centro de La Fortuna. Habitaciones sencillas con terraza, restaurante propio y jardines. Una de las opciones habituales para quien quiere quedarse cerca del pueblo sin pagar tarifa de resort.',
 'A mid-range hotel on the road to the volcano, a kilometre from downtown. Simple rooms with terraces, an on-site restaurant and gardens.',
 'Carretera al Volcán Arenal, 1 km del centro','moderado','parcial',
 '{"tiene_restaurante":true}'),

('resorts','Nayara Gardens','nayara-gardens',
 null,null,null,null,
 'Eco-lujo entre jardines, con villas y pozas privadas.',
 'Eco-luxury among gardens, with villas and private pools.',
 'Complejo de eco-lujo junto al volcán, con villas repartidas entre jardines y bosque. Es de los hoteles más premiados del país. Su propiedad hermana, Nayara Springs, es solo para adultos y cada villa tiene su poza termal privada.',
 'An eco-luxury complex beside the volcano, with villas spread among gardens and forest. One of the most awarded hotels in the country.',
 'Carretera a Nuevo Arenal, La Fortuna','lujo','pendiente',
 '{"tipo_habitacion":"villa"}'),

('resorts','Arenal Kioro Suites & Spa','arenal-kioro-suites-spa',
 null,null,null,null,
 'Suites con ventanal frontal al volcán y termales propias.',
 'Suites facing the volcano head-on, with on-site hot springs.',
 'Suites amplias con ventanal frontal al cono del Arenal, rodeadas de quebradas y jardines. Tiene aguas termales propias en la finca y spa. Está sobre la carretera al parque, en el tramo con la vista más despejada del volcán.',
 'Large suites with floor-to-ceiling windows facing the Arenal cone. Its own thermal springs on the grounds and a spa.',
 'Carretera al Parque Nacional Volcán Arenal','lujo','pendiente',
 '{"tiene_aguas_termales":true,"tiene_spa":true}'),

('hostales','Arenal Backpackers Resort','arenal-backpackers-resort',
 null,null,null,'https://arenalbackpackers.com',
 'Hostal en el centro con piscina y vista al volcán.',
 'Downtown hostel with a pool and volcano views.',
 'Hostal en el centro de La Fortuna con vista al volcán y piscina al aire libre. Mezcla dormitorios compartidos, habitaciones privadas y tiendas safari, así que sirve tanto al mochilero como a quien quiere privacidad barata. Wifi, guarda equipaje y bar propio.',
 'A hostel in downtown La Fortuna with volcano views and an outdoor pool. Shared dorms, private rooms and safari tents.',
 'Centro de La Fortuna','economico','parcial',
 '{"tiene_piscina":true,"tipos_habitacion":["dormitorio","privada","tienda safari"]}'),

('hostales','Selina La Fortuna','selina-la-fortuna',
 null,null,null,null,
 'Hostal con río propio, yoga diario y cocina compartida.',
 'Hostel with its own river, daily yoga and a shared kitchen.',
 'Hostal con vista directa al volcán y un río que cruza la propiedad. Tiene restaurante, jardín, bar, cocina compartida y sesiones diarias de yoga y meditación. Perfil más de estadía larga y trabajo remoto que de paso rápido.',
 'A hostel with a direct volcano view and a river running through the property. More of a long-stay and remote-work crowd.',
 'La Fortuna de San Carlos','economico','pendiente',
 '{"tiene_cocina_compartida":true,"tiene_yoga":true}'),

('cocina-internacional','Don Rufino','don-rufino',
 null,'+50624799997','+50684664288','https://donrufino.com',
 'Cocina de autor con raíz tica, en el centro desde 2005.',
 'Chef-driven cooking with Costa Rican roots, downtown since 2005.',
 'Cocina contemporánea internacional con esencia costarricense, en pleno centro desde 2005. Es la dirección a la que va la gente de La Fortuna cuando hay algo que celebrar: carta corta y bien ejecutada, buena bodega de vinos y una barra que se llena de noche. Abre todos los días de once de la mañana a once de la noche.',
 'Contemporary international cooking with a Costa Rican core, in the heart of town since 2005. Where locals go when there is something to celebrate. Open daily 11am to 11pm.',
 'Diagonal a la Gasolinera La Fortuna, centro','alto','verificado',
 '{"abre":"11:00","cierra":"23:00","opera_desde":2005,"acepta_reservas":true}'),

('comida-tipica','La Choza de Laurel','la-choza-de-laurel',
 'info@lachozadelaurel.com','+50624797063',null,'https://lachozadelaurel.com',
 'Comida típica bajo rancho, con gallinas asadas al fogón.',
 'Traditional food under a thatched roof, with chickens on the fire.',
 'Uno de los restaurantes de comida típica más conocidos de la región. Ambiente de rancho tradicional, cocina a la vista y las gallinas asándose al fogón en la entrada, que es su marca de la casa. Casados, olla de carne y platos de siempre, servidos rápido y bien.',
 'One of the best-known traditional Costa Rican restaurants in the region. A traditional ranch setting, an open kitchen and chickens roasting over the fire at the entrance.',
 '300 metros oeste del Parque Central','moderado','verificado',
 '{"telefono_alterno":"+50624797069","especialidad":"gallina asada al fogon"}'),

('comida-tipica','Pollo Fortuneño','pollo-fortuneno',
 null,'+50689910217',null,null,
 'Pollo y costillas a la leña, el plato insignia del pueblo.',
 'Wood-fired chicken and ribs, the town signature plate.',
 'Pollo y costillas asadas a la leña en parrilla a la vista. El Pollo Fortuneño es el plato que le dio el nombre y lo que viene a comer la gente. Sencillo, abundante y a precio de pueblo, no de zona turística. Acepta todas las tarjetas.',
 'Chicken and ribs grilled over wood on an open barbecue. Simple, generous and priced like a local spot, not a tourist one.',
 'Calle 474, frente al Colono, La Fortuna','economico','verificado',
 '{"abre":"11:00","cierra":"22:00","especialidad":"pollo a la lena"}'),

('cocina-internacional','Restaurante Café Mediterráneo','restaurante-cafe-mediterraneo',
 null,null,null,null,
 'Pizza al horno de leña y pasta hecha a mano.',
 'Wood-fired pizza and handmade pasta.',
 'Pizzas al horno de leña y pasta hecha en casa, en un local pequeño del centro. Es la alternativa italiana del pueblo y suele llenarse temprano, así que conviene llegar antes de las siete.',
 'Wood-fired pizzas and house-made pasta in a small spot downtown. It fills early, so come before seven.',
 'Centro de La Fortuna','moderado','pendiente',
 '{"especialidad":"pizza al horno de lena"}'),

('cocina-internacional','Mirador Steak House','mirador-steak-house',
 null,null,null,null,
 'Carnes a la parrilla con el volcán de frente.',
 'Grilled steaks with the volcano in full view.',
 'Parrilla con vista abierta al volcán, especializada en cortes de carne y con carta nacional e internacional. La vista es el argumento principal: conviene reservar mesa cerca del ventanal y llegar antes del atardecer.',
 'A grill with an open view of the volcano, specialising in steaks. Book a window table and get there before sunset.',
 'La Fortuna de San Carlos','alto','pendiente',
 '{"especialidad":"cortes de carne"}'),

('comida-tipica','Tierra Mía Restaurante','tierra-mia-restaurante',
 null,null,null,null,
 'Lomito y pechuga con puré sazonado, fuera del circuito.',
 'Tenderloin and chicken breast, off the tourist strip.',
 'Restaurante fuera del circuito más transitado, muy bien valorado por quienes lo encuentran. El lomito y la pechuga son lo que recomienda todo el mundo, acompañados de un puré bien sazonado y salsas de la casa.',
 'A restaurant off the busiest strip, highly rated by those who find it. The tenderloin and the chicken breast are what everyone recommends.',
 'La Fortuna de San Carlos','moderado','pendiente','{}'),

('tours-aventura','Desafío Adventure Company','desafio-adventure-company',
 null,'+50624790020',null,'https://www.desafiocostarica.com',
 'El operador pionero de la zona, en activo desde 1992.',
 'The area pioneering outfitter, running since 1992.',
 'Operador pionero de la zona, fundado en 1992 y todavía en manos locales. Cubre casi todo lo que se puede hacer en Arenal: rafting, canyoning, bicicleta, caminatas, avistamiento de aves, kayak, paddle, clases de cocina y traslados con tour incluido hacia Monteverde.',
 'The areas pioneering outfitter, founded in 1992 and still locally owned. Rafting, canyoning, biking, hiking, birdwatching, kayaking, cooking classes and transfers with a tour built in.',
 'Detrás de la Iglesia Católica de La Fortuna','moderado','verificado',
 '{"opera_desde":1992,"telefono_alterno":"+50624790200","telefono_eeuu":"+18558180020"}'),

('canopy','Arenal Mundo Aventura','arenal-mundo-aventura',
 'reservaciones@arenalmundoaventura.com','+50624799762',null,'https://www.arenalmundoaventura.com',
 'Parque de canopy con vista a las cataratas Fortuna y Pino Blanco.',
 'Zip-line park overlooking the Fortuna and Pino Blanco waterfalls.',
 'Parque de aventura con tres modalidades de canopy: el AMA Extreme de siete cables y el BIG AMA de doce, ambos con vista a las cataratas Fortuna y Pino Blanco. Completan la oferta cabalgatas, caminatas y rappel.',
 'An adventure park with three zip-line circuits, plus horseback riding, hikes and rappelling, overlooking the Fortuna and Pino Blanco waterfalls.',
 '1,5 km sur de la Iglesia Católica, La Fortuna','moderado','verificado',
 '{"cables_ama_extreme":7,"cables_big_ama":12,"telefono_alterno":"+50624799156"}'),

('canopy','Sky Adventures Arenal Park','sky-adventures-arenal-park',
 null,null,'+50685450475','https://skyadventures.travel',
 'Canopy, telecabina y puentes colgantes en un mismo parque.',
 'Zip lines, aerial tram and hanging bridges in one park.',
 'Parque que junta tres cosas que en otros lados hay que hacer por separado: el Sky Trek de canopy, el Sky Tram que sube en telecabina y el Sky Walk de puentes colgantes. Incluye jardín de colibríes y orquídeas, restaurante y transporte desde los hoteles.',
 'A park that bundles three things you would otherwise do separately: Sky Trek zip lines, the Sky Tram gondola and the Sky Walk hanging bridges.',
 'Ruta 142, La Fortuna, San Carlos','alto','parcial',
 '{"atracciones":["Sky Trek","Sky Tram","Sky Walk"],"tiene_restaurante":true}'),

('canyoning','Pure Trek Canyoning','pure-trek-canyoning',
 null,null,null,'https://puretrek.com',
 'Rappel en cataratas en cañón propio, desde 2001.',
 'Waterfall rappelling in its own canyon, since 2001.',
 'Operador de canyoning y rappel en cataratas desde 2001, con cañón propio y guías certificados. El recorrido baja por varias caídas dentro del bosque e incluye el llamado Monkey Drop. Es medio día y no exige experiencia previa.',
 'A canyoning and waterfall-rappelling operator since 2001, with its own canyon and certified guides. Half a day, no previous experience needed.',
 'La Fortuna de San Carlos','alto','parcial',
 '{"opera_desde":2001,"duracion":"medio dia"}'),

('rafting','Wave Expeditions','wave-expeditions',
 null,null,null,'https://www.waveexpeditions.com',
 'Rafting en los ríos de la zona y combinados de aventura.',
 'Rafting on the local rivers, plus combo adventures.',
 'Operador de rafting y aventura de La Fortuna. Corre los ríos de la zona en distintos grados de dificultad, desde el familiar hasta el técnico, y arma combinados de día completo con canyoning y canopy.',
 'A rafting and adventure operator based in La Fortuna, running the areas rivers at various difficulty grades.',
 'La Fortuna de San Carlos','moderado','parcial','{}'),

('alquiler-de-autos','Adobe Rent a Car La Fortuna','adobe-rent-a-car-la-fortuna',
 null,'+50625424848',null,'https://www.adobecar.com',
 'Alquiler de vehículos y shuttles, con oficina en el centro.',
 'Car rental and shuttles, with an office downtown.',
 'Sucursal en el centro de La Fortuna de una de las arrendadoras nacionales más establecidas. Alquiler de vehículos, incluidos cuatro por cuatro para los caminos de la zona, y shuttles compartidos y privados hacia Monteverde, San José y los aeropuertos.',
 'The downtown branch of one of the countrys most established rental companies. Car rental including four-wheel drives, plus shared and private shuttles.',
 'Calle 466, entre Ruta 142 y Avenida 325, centro','moderado','verificado',
 '{"servicios":["alquiler de vehiculos","shuttle compartido","shuttle privado"]}'),

('shuttles','Interbus','interbus-la-fortuna',
 null,null,null,'https://www.interbusonline.com',
 'Shuttles compartidos a Monteverde, San José y Liberia.',
 'Shared shuttles to Monteverde, San Jose and Liberia.',
 'Servicio de shuttles compartidos y privados con salidas frecuentes entre La Fortuna, Monteverde, San José y Liberia. Busetas con aire acondicionado, conductores bilingües y recogida en el hotel. Es la alternativa habitual al bus público para quien no alquila carro.',
 'Shared and private shuttle service with frequent departures between La Fortuna, Monteverde, San Jose and Liberia. Air-conditioned vans, bilingual drivers and hotel pickup.',
 'Recogida en hoteles de La Fortuna','moderado','parcial',
 '{"destinos":["Monteverde","San Jose","Liberia","Guanacaste"],"recoge_en_hotel":true}')

)
insert into destinos.dst_negocio (
  destino_id, categoria_id, nombre, babosa_es, babosa_en, email, telefono,
  telefono_whatsapp, sitio_web, resumen_es, resumen_en, descripcion_es,
  descripcion_en, direccion, rango_precio, estado_publicacion,
  estado_verificacion, fuente_dato, atributos, publicado_en
)
select d.id, c.id, x.nombre, x.babosa, x.babosa, x.email, x.telefono,
       x.whatsapp, x.sitio_web, x.resumen_es, x.resumen_en, x.descripcion_es,
       x.descripcion_en, x.direccion,
       x.rango_precio::destinos.rango_precio,
       'publicado'::destinos.estado_publicacion,
       x.verificacion::destinos.estado_verificacion,
       'siembra_manual'::destinos.fuente_dato,
       x.atributos::jsonb, now()
  from datos x
  join destinos.dst_destino  d on d.babosa = 'la-fortuna'
  join destinos.dst_categoria c on c.babosa_es = x.categoria;
